CREATE TABLE Products (
    -- Unique, auto-incrementing primary key
    id              SERIAL PRIMARY KEY,

    -- Common Name (Set as NOT NULL, as every plant must have a common name)
    name            VARCHAR(255) NOT NULL,

    -- Latin/Scientific Name
    scientific_name VARCHAR(255),

    -- Category/Type (e.g., 'Houseplant', 'Fruit')
    plant_type      VARCHAR(100),

    -- Plant description (TEXT is suitable for longer content)
    description     TEXT,

    -- Direct image URL (TEXT is suitable for potentially long URLs)
    image_url       TEXT,

    -- URL to the source/license page
    source_page     TEXT
);

INSERT INTO Products (name, scientific_name, plant_type, description, image_url, source_page)
VALUES
  ('Snake Plant', 'Dracaena trifasciata', 'Houseplant', 'A hardy houseplant with stiff, sword-like leaves. It tolerates low light and irregular watering.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Snake_Plant_(Sansevieria_trifasciata_%27Laurentii%27)_1.jpg', 'https://commons.wikimedia.org/wiki/File:Snake_Plant_(Sansevieria_trifasciata_%27Laurentii%27)_1.jpg'),
  ('Peace Lily', 'Spathiphyllum wallisii', 'Houseplant', 'Known for its white spoon-shaped flowers and glossy green leaves. It droops when thirsty.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Peace_lily_-_1.jpg', 'https://commons.wikimedia.org/wiki/File:Peace_lily_-_1.jpg'),
  ('Lavender', 'Lavandula angustifolia', 'Herb', 'An aromatic herb with purple flowers, often used for its calming scent and essential oils.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lavandula_angustifolia_002.JPG', 'https://commons.wikimedia.org/wiki/File:Lavandula_angustifolia_002.JPG'),
  ('Sunflower', 'Helianthus annuus', 'Flower', 'A tall annual plant with massive yellow flower heads that track the sun''s movement.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Helianthus_annuus_sunflower.jpg', 'https://commons.wikimedia.org/wiki/File:Helianthus_annuus_sunflower.jpg'),
  ('Aloe Vera', 'Aloe barbadensis miller', 'Succulent', 'A succulent species with thick fleshy leaves containing a soothing gel used for skin burns.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Aloe_vera.jpg', 'https://commons.wikimedia.org/wiki/File:Aloe_vera.jpg'),
  ('Pothos', 'Epipremnum aureum', 'Houseplant', 'A popular trailing houseplant with heart-shaped leaves, often variegated with yellow or white.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Epipremnum_aureum1.jpg', 'https://commons.wikimedia.org/wiki/File:Epipremnum_aureum1.jpg'),
  ('Rubber Plant', 'Ficus elastica', 'Houseplant', 'An impressive indoor tree with large, glossy, dark green or burgundy leaves.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ficus_elastica.jpg', 'https://commons.wikimedia.org/wiki/File:Ficus_elastica.jpg'),
  ('Fiddle-Leaf Fig', 'Ficus lyrata', 'Houseplant', 'A trendy indoor tree with large, violin-shaped leaves that require bright, filtered light.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ficus_lyrata1.jpg', 'https://commons.wikimedia.org/wiki/File:Ficus_lyrata1.jpg'),
  ('Basil', 'Ocimum basilicum', 'Herb', 'A culinary herb essential in Italian cuisine, known for its sweet, peppery aroma.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ocimum_basilicum-001.jpg', 'https://commons.wikimedia.org/wiki/File:Ocimum_basilicum-001.jpg'),
  ('Tomato', 'Solanum lycopersicum', 'Vegetable', 'A widely cultivated edible berry (vegetable) available in thousands of varieties.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Solanum_lycopersicum_cc.JPG', 'https://commons.wikimedia.org/wiki/File:Solanum_lycopersicum_cc.JPG'),
  ('Tulip', 'Tulipa', 'Flower', 'A bulbous spring-flowering plant with large, cup-shaped flowers in vibrant colors.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tulipa_flower.jpg', 'https://commons.wikimedia.org/wiki/File:Tulipa_flower.jpg'),
  ('Orchid', 'Orchidaceae', 'Flower', 'A diverse family of flowering plants with blooms that are often colorful and fragrant.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Orchid(Orchidaceae).JPG', 'https://commons.wikimedia.org/wiki/File:Orchid(Orchidaceae).JPG'),
  ('Spider Plant', 'Chlorophytum comosum', 'Houseplant', 'A classic houseplant with arching striped leaves that produces small ''plantlets'' on stems.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chlorophytum_comosum_Ampel.jpg', 'https://commons.wikimedia.org/wiki/File:Chlorophytum_comosum_Ampel.jpg'),
  ('Fern', 'Nephrolepis exaltata', 'Fern', 'A lush, green plant with feathery fronds that thrives in humid environments.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Nephrolepis_exaltata.jpg', 'https://commons.wikimedia.org/wiki/File:Nephrolepis_exaltata.jpg'),
  ('Mint', 'Mentha spicata', 'Herb', 'A fast-growing aromatic herb commonly used in teas, desserts, and cocktails.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mentha_spicata.jpg', 'https://commons.wikimedia.org/wiki/File:Mentha_spicata.jpg'),
  ('Rose', 'Rosa', 'Flower', 'A woody perennial flowering plant known for its beautiful blooms and sharp thorns.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rosa_rubiginosa_1.jpg', 'https://commons.wikimedia.org/wiki/File:Rosa_rubiginosa_1.jpg'),
  ('ZZ Plant', 'Zamioculcas zamiifolia', 'Houseplant', 'A drought-tolerant plant with waxy, dark green leaves that requires very little maintenance.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamioculcas_zamiifolia.jpg', 'https://commons.wikimedia.org/wiki/File:Zamioculcas_zamiifolia.jpg'),
  ('Golden Barrel Cactus', 'Echinocactus grusonii', 'Cactus', 'A round, spiny cactus native to Mexico, often grown as an ornamental plant.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Echinocactus_grusonii.jpg', 'https://commons.wikimedia.org/wiki/File:Echinocactus_grusonii.jpg'),
  ('Hydrangea', 'Hydrangea macrophylla', 'Shrub', 'A shrub famous for its large flower heads which can change color based on soil pH.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hydrangea_macrophylla_2.jpg', 'https://commons.wikimedia.org/wiki/File:Hydrangea_macrophylla_2.jpg'),
  ('Japanese Maple', 'Acer palmatum', 'Tree', 'A small tree cultivated for its attractive leaf shapes and brilliant autumn colors.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Acer_palmatum.jpg', 'https://commons.wikimedia.org/wiki/File:Acer_palmatum.jpg'),
  ('Garden Strawberry', 'Fragaria x ananassa', 'Fruit/Vegetable', 'A hybrid species widely grown for its sweet, red heart-shaped fruit.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fragaria_x_ananassa_Toscana_452.jpg', 'https://commons.wikimedia.org/wiki/File:Fragaria_x_ananassa_Toscana_452.jpg'),
  ('Orange', 'Citrus x sinensis', 'Fruit/Tree', 'The fruit of the citrus species Citrus x sinensis in the family Rutaceae.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Citrus_sinensis.jpg', 'https://commons.wikimedia.org/wiki/File:Citrus_sinensis.jpg'),
  ('Pineapple', 'Ananas comosus', 'Fruit', 'A tropical plant with an edible multiple fruit consisting of coalesced berries.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pineapple_(Ananas_comosus)_(2858289060).jpg', 'https://commons.wikimedia.org/wiki/File:Pineapple_(Ananas_comosus)_(2858289060).jpg'),
  ('Wild Carrot', 'Daucus carota', 'Vegetable', 'A white, flowering plant in the family Apiaceae, also known as Queen Anne''s lace.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Daucus_carota_qtl3.jpg', 'https://commons.wikimedia.org/wiki/File:Daucus_carota_qtl3.jpg'),
  ('Cilantro', 'Coriandrum sativum', 'Herb', 'An annual herb whose fresh leaves and dried seeds are used in cooking.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Coriandrum_sativum_002.JPG', 'https://commons.wikimedia.org/wiki/File:Coriandrum_sativum_002.JPG'),
  ('Oregano', 'Origanum vulgare', 'Herb', 'A flowering plant in the mint family, sometimes called wild marjoram.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Origanum_vulgare_001.JPG', 'https://commons.wikimedia.org/wiki/File:Origanum_vulgare_001.JPG'),
  ('Turmeric', 'Curcuma longa', 'Herb/Spice', 'A flowering plant of the ginger family, the roots of which are used in cooking.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Curcuma_longa_001.JPG', 'https://commons.wikimedia.org/wiki/File:Curcuma_longa_001.JPG'),
  ('Rosemary', 'Salvia rosmarinus', 'Herb', 'A woody, perennial herb with fragrant, evergreen, needle-like leaves.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Salvia_rosmarinus_168046536.jpg', 'https://commons.wikimedia.org/wiki/File:Salvia_rosmarinus_168046536.jpg'),
  ('Sage', 'Salvia officinalis', 'Herb', 'A perennial, evergreen subshrub, with woody stems, grayish leaves, and blue to purplish flowers.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Salvia_officinalis_003.JPG', 'https://commons.wikimedia.org/wiki/File:Salvia_officinalis_003.JPG'),
  ('Common Daisy', 'Bellis perennis', 'Flower', 'A common European species of the family Asteraceae, often considered the archetypal species of that name.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bellis_perennis_001.JPG', 'https://commons.wikimedia.org/wiki/File:Bellis_perennis_001.JPG'),
  ('Chrysanthemum', 'Chrysanthemum morifolium', 'Flower', 'Flowering plants of the genus Chrysanthemum in the family Asteraceae.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chrysanthemum_morifolium_j03.jpg', 'https://commons.wikimedia.org/wiki/File:Chrysanthemum_morifolium_j03.jpg'),
  ('Jade Plant', 'Crassula ovata', 'Succulent', 'A succulent plant with small pink or white flowers and thick leaves.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Crassula_ovata_700.jpg', 'https://commons.wikimedia.org/wiki/File:Crassula_ovata_700.jpg'),
  ('Heartleaf Philodendron', 'Philodendron hederaceum', 'Houseplant', 'A species of flowering plant in the family Araceae, native to Central America and the Caribbean.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Philodendron_hederaceum_kz1.jpg', 'https://commons.wikimedia.org/wiki/File:Philodendron_hederaceum_kz1.jpg'),
  ('English Oak', 'Quercus robur', 'Tree', 'A species of flowering plant in the beech and oak family, Fagaceae.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Quercus_robur.png', 'https://commons.wikimedia.org/wiki/File:Quercus_robur.png'),
  ('Southern Magnolia', 'Magnolia grandiflora', 'Tree', 'A tree of the family Magnoliaceae native to the southeastern United States.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Magnolia_grandiflora_(6).JPG', 'https://commons.wikimedia.org/wiki/File:Magnolia_grandiflora_(6).JPG'),
  ('Hibiscus', 'Hibiscus rosa-sinensis', 'Flower/Shrub', 'A flowering plant in the Malvaceae family, widely grown in the tropics and subtropics.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hibiscus_rosa-sinensis_13zz.jpg', 'https://commons.wikimedia.org/wiki/File:Hibiscus_rosa-sinensis_13zz.jpg'),
  ('Carnation', 'Dianthus caryophyllus', 'Flower', 'A species of Dianthus. It is likely native to the Mediterranean region.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dianthus_caryophyllus_Chabaud_%27Etincelant%27,_Elfenau.jpg', 'https://commons.wikimedia.org/wiki/File:Dianthus_caryophyllus_Chabaud_%27Etincelant%27,_Elfenau.jpg'),
  ('String of Pearls', 'Senecio rowleyanus', 'Succulent', 'A flowering plant in the daisy family Asteraceae, known for its bead-like leaves.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Senecio_rowleyanus.jpg', 'https://commons.wikimedia.org/wiki/File:Senecio_rowleyanus.jpg'),
  ('Madonna Lily', 'Lilium candidum', 'Flower', 'A plant in the true lily family. It is native to the Balkans and Middle East.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lilium_candidum_2_(lit).jpg', 'https://commons.wikimedia.org/wiki/File:Lilium_candidum_2_(lit).jpg'),
  ('Chinese Money Plant', 'Pilea peperomioides', 'Houseplant', 'A species of flowering plant in the nettle family Urticaceae, native to Yunnan province in China.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pilea_peperomioides_Kilp-piilea_C_IMG_5317.JPG', 'https://commons.wikimedia.org/wiki/File:Pilea_peperomioides_Kilp-piilea_C_IMG_5317.JPG'),
  ('Spineless Yucca', 'Yucca elephantipes', 'Houseplant/Tree', 'A yucca species that is native to Mexico and Central America.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yucca_elephantipes_15zz.jpg', 'https://commons.wikimedia.org/wiki/File:Yucca_elephantipes_15zz.jpg'),
  ('Moso Bamboo', 'Phyllostachys edulis', 'Grass', 'A temperate species of giant timber bamboo native to China and Taiwan.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Phyllostachys_edulis_01.jpg', 'https://commons.wikimedia.org/wiki/File:Phyllostachys_edulis_01.jpg'),
  ('Tasmanian Blue Gum', 'Eucalyptus globulus', 'Tree', 'An evergreen tree, one of the most widely cultivated trees native to Australia.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Eucalyptus_globulus_g1.jpg', 'https://commons.wikimedia.org/wiki/File:Eucalyptus_globulus_g1.jpg'),
  ('Spinach', 'Spinacia oleracea', 'Vegetable', 'A leafy green flowering plant native to central and western Asia.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Spinacia_oleracea_Spinazie_bloeiend.jpg', 'https://commons.wikimedia.org/wiki/File:Spinacia_oleracea_Spinazie_bloeiend.jpg'),
  ('Grape Vine', 'Vitis vinifera', 'Fruit/Vine', 'A species of Vitis, native to the Mediterranean region, central Europe, and southwestern Asia.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vitis_vinifera.jpg', 'https://commons.wikimedia.org/wiki/File:Vitis_vinifera.jpg'),
  ('Parsley', 'Petroselinum crispum', 'Herb', 'A species of flowering plant in the family Apiaceae, native to the central Mediterranean region.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Petroselinum_crispum_003.JPG', 'https://commons.wikimedia.org/wiki/File:Petroselinum_crispum_003.JPG'),
  ('Cinnamon', 'Cinnamomum verum', 'Spice/Tree', 'A small evergreen tree belonging to the family Lauraceae, native to Sri Lanka.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cinnamomum_verum_1zz.jpg', 'https://commons.wikimedia.org/wiki/File:Cinnamomum_verum_1zz.jpg'),
  ('Jasmine', 'Jasminum officinale', 'Flower/Vine', 'A species of flowering plant in the olive family Oleaceae, native to the Caucasus.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jasminum_officinale-IMG_3470.jpg', 'https://commons.wikimedia.org/wiki/File:Jasminum_officinale-IMG_3470.jpg'),
  ('Dieffenbachia', 'Dieffenbachia seguine', 'Houseplant', 'A species of Dieffenbachia native to the tropical Americas.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dieffenbachia_seguine_002.JPG', 'https://commons.wikimedia.org/wiki/File:Dieffenbachia_seguine_002.JPG'),
  ('Christmas Cactus', 'Schlumbergera buckleyi', 'Houseplant/Cactus', 'A hybrid cactus known for blooming during the winter holidays.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Schlumbergera_buckleyi_WPC.jpg', 'https://commons.wikimedia.org/wiki/File:Schlumbergera_buckleyi_WPC.jpg'),
  ('Bird of Paradise', 'Strelitzia reginae', 'Flower', 'A species of flowering plant indigenous to South Africa, famous for its bird-like flowers.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Strelitzia_Reginae_(2124333853).jpg', 'https://commons.wikimedia.org/wiki/File:Strelitzia_Reginae_(2124333853).jpg'),
  ('Maidenhair Fern', 'Adiantum capillus-veneris', 'Fern', 'A species of fern in the genus Adiantum with delicate, fan-shaped fronds.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Adiantum_capillus-veneris_(USDA).jpg', 'https://commons.wikimedia.org/wiki/File:Adiantum_capillus-veneris_(USDA).jpg'),
  ('Saguaro', 'Carnegiea gigantea', 'Cactus', 'A tree-like cactus species in the monotypic genus Carnegiea, native to the Sonoran Desert.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Carnegiea_gigantea_3zz.jpg', 'https://commons.wikimedia.org/wiki/File:Carnegiea_gigantea_3zz.jpg'),
  ('Thyme', 'Thymus vulgaris', 'Herb', 'A woody, perennial herb with small, fragrant leaves used for culinary purposes.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Thymus_vulgaris_001.JPG', 'https://commons.wikimedia.org/wiki/File:Thymus_vulgaris_001.JPG'),
  ('Lemon', 'Citrus limon', 'Fruit/Tree', 'A species of small evergreen tree in the flowering plant family Rutaceae.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Citrus_limon.jpg', 'https://commons.wikimedia.org/wiki/File:Citrus_limon.jpg'),
  ('Banana', 'Musa acuminata', 'Fruit', 'A species of banana native to Southern Asia, one of the ancestors of modern edible bananas.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Musa_acuminata_fruit.jpg', 'https://commons.wikimedia.org/wiki/File:Musa_acuminata_fruit.jpg'),
  ('Watermelon', 'Citrullus lanatus', 'Fruit', 'A flowering plant species of the Cucurbitaceae family, originally from West Africa.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Citrullus_lanatus.jpg', 'https://commons.wikimedia.org/wiki/File:Citrullus_lanatus.jpg'),
  ('Ginger', 'Zingiber officinale', 'Herb/Spice', 'A flowering plant whose rhizome, ginger root or ginger, is widely used as a spice.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zingiber_officinale_roots.jpg', 'https://commons.wikimedia.org/wiki/File:Zingiber_officinale_roots.jpg'),
  ('Garlic', 'Allium sativum', 'Vegetable/Herb', 'A species in the onion genus, Allium. Its close relatives include the onion and shallot.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Allium_sativum_001.JPG', 'https://commons.wikimedia.org/wiki/File:Allium_sativum_001.JPG'),
  ('Marigold', 'Tagetes patula', 'Flower', 'A species of flowering plant in the daisy family, native to Mexico and Guatemala.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tagetes_patula_001.JPG', 'https://commons.wikimedia.org/wiki/File:Tagetes_patula_001.JPG'),
  ('Sacred Lotus', 'Nelumbo nucifera', 'Aquatic Flower', 'One of two extant species of aquatic plant in the family Nelumbonaceae.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Nelumbo_nucifera_001.JPG', 'https://commons.wikimedia.org/wiki/File:Nelumbo_nucifera_001.JPG'),
  ('Geranium', 'Pelargonium zonale', 'Flower', 'A species of Pelargonium native to southern Africa, widely grown as an ornamental plant.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pelargonium_zonale_001.JPG', 'https://commons.wikimedia.org/wiki/File:Pelargonium_zonale_001.JPG'),
  ('Petunia', 'Petunia x atkinsiana', 'Flower', 'A plant of the nightshade family, genetically modified for colorful garden blooms.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Petunia_x_atkinsiana_001.JPG', 'https://commons.wikimedia.org/wiki/File:Petunia_x_atkinsiana_001.JPG'),
  ('African Violet', 'Streptocarpus ionanthus', 'Houseplant', 'A species of flowering plant in the family Gesneriaceae, native to Tanzania.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Saintpaulia_ionantha_01.jpg', 'https://commons.wikimedia.org/wiki/File:Saintpaulia_ionantha_01.jpg'),
  ('Flamingo Lily', 'Anthurium andraeanum', 'Houseplant', 'A flowering plant species in the family Araceae that is native to Colombia and Ecuador.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Anthurium_andraeanum_001.JPG', 'https://commons.wikimedia.org/wiki/File:Anthurium_andraeanum_001.JPG'),
  ('Scots Pine', 'Pinus sylvestris', 'Tree', 'A species of pine that is native to Eurasia, ranging from Western Europe to Eastern Siberia.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pinus_sylvestris_001.JPG', 'https://commons.wikimedia.org/wiki/File:Pinus_sylvestris_001.JPG'),
  ('Weeping Willow', 'Salix babylonica', 'Tree', 'A species of willow native to dry areas of northern China, but cultivated for millennia.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Salix_babylonica_001.JPG', 'https://commons.wikimedia.org/wiki/File:Salix_babylonica_001.JPG'),
  ('Silver Birch', 'Betula pendula', 'Tree', 'A species of tree in the family Betulaceae, native to Europe and parts of Asia.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Betula_pendula_001.JPG', 'https://commons.wikimedia.org/wiki/File:Betula_pendula_001.JPG'),
  ('Cherry Blossom', 'Prunus serrulata', 'Tree', 'A species of cherry native to Japan, Korea and China, used for ornamental use and festivals.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Prunus_serrulata_001.JPG', 'https://commons.wikimedia.org/wiki/File:Prunus_serrulata_001.JPG'),
  ('Broccoli', 'Brassica oleracea var. italica', 'Vegetable', 'An edible green plant in the cabbage family whose large flowering head is eaten as a vegetable.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Broccoli_and_cross_section_edit.jpg', 'https://commons.wikimedia.org/wiki/File:Broccoli_and_cross_section_edit.jpg');
